modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"

[[mods]]
modId="kzeaddon"
version="2.0.0"
displayName="KZEAddon"
authors="tedo0627"
description='''
This mod helps you play with a KaedeZombieEscape server.
'''

[[dependencies.kzeaddon]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kzeaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
