modLoader="kotlinforforge"
loaderVersion="[3,)"
license="MIT License"

[[mods]]
modId="kzeaddon"
version="3.0.1"
displayName="KZEAddon"
authors="tedo0627"
description='''
KZEのプレイをサポートするmod
'''

[[dependencies.kzeaddon]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kzeaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
