modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="kzeaddon"
version="1.0.2"
displayName="KZEAddon"
displayURL="https://github.com/tedo0627/KZEAddon"
authors="tedo0627"
description="This mod helps you play with a KaedeZombieEscape server."
[[dependencies.kzeaddon]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.kzeaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15.2]"
    ordering="NONE"
    side="BOTH"
